project_id = "fckvwhsfabjfnjvarczk"

[functions.exam-buddy]
verify_jwt = false

[functions.study-planner]
verify_jwt = false

[functions.exam-impact]
verify_jwt = false

[functions.generate-short-notes]
verify_jwt = false